### ISSUE TITLE
Catalogue and Recommendations are largely the same

### ISSUE THREAD

**Issue by dagwieers** [michaelarnauts/plugin.video.vtm.go#119]
**Is your feature request related to a problem? Please describe.**
The Catalogue and Recommendations are largely the same.
The Catalogue seems to be a subset of the Recommendations.
In the Kids zone they are almost identical.

**Describe the solution you'd like**
I would either merge them together, or create 2 separate complementary sections.

**Comment by michaelarnauts** [comment]
The recommendations seem to have maximum 20 entries per category, while the Catalog shows all entries. I think they put the most popular items in the recommendations.

I don't think they should be merged, since they both are a different view on the same catalog. It's up to VTM GO to create categories for this. Nevertheless, I think the most important items in the recommendations are "Aanbevolen voor jou" and "Nieuw op VTM GO", but I wouldn't go so far as to filter the rest out.
