### ISSUE TITLE
Why no first alfa or beta release?

### ISSUE THREAD

**Issue by peno64** [michaelarnauts/plugin.video.vtm.go#29]
It is only by coincidence that I discovered your addon. It works good for the non-live content. I use it on a rpi3 with libreelec. It indeed crashes with luve streams. But for the luve streams there are 2 or 3 other addons that do work. For the non-live content thisis at this moment the only addon that can play vtm go content. So a big advantage and its disadvantage is not that bad. So why not make a first release without the live content?

**Comment by michaelarnauts** [comment]
The problem is that for most content, only the last part (after the last ad) is played because inputstream adaptive doesn't support Periods (yet).

I plan to make a release when this is fixed, and live TV doesn't crash on Linux. I want to avoid bugreports for those obvious things.

I the meanwhile, you can download a repo zip or git clone in your add-ons dir.
